# Generated by Django 3.1.2 on 2020-10-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tx_name', max_length=104, unique=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
    ]
